-- تشغيل هذا الكود في Supabase SQL Editor لإنشاء الجدول المطلوب

create table barcode_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  input_code text not null,
  check_digit text not null,
  full_gtin text not null
);

-- (اختياري) تفعيل الوصول للقراءة والكتابة للجميع (للتسهيل في البداية)
-- ينصح بضبط سياسات RLS لاحقاً للأمان
alter table barcode_history enable row level security;

create policy "Enable all access for all users"
on barcode_history
for all
using (true)
with check (true);
